version: '3.13'

volumes:
  pgdata:

networks:
  backend:

services:

  pg_db:
    image: postgres:14.3-alpine3.16
    container_name: ad_site_db
    environment:
      POSTGRES_DB: ad_site_pgdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
#      POSTGRES_DB: ${DB_NAME}
#      POSTGRES_USER: ${DB_USER}
#      POSTGRES_PASSWORD: ${DB_PASSWORD}
#    ports:
#      - '5432:${DB_PORT}'
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1G

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "5050:80"
    container_name: pgadmin
    depends_on:
      - pg_db
    environment:
      PGADMIN_DEFAULT_EMAIL: "aaa@yandex.ru"
      PGADMIN_DEFAULT_PASSWORD: "111"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - ./services/pgadmin:/var/lib/pgadmin
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1G